backend:
  name: git-gateway
  branch: devel-www # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: 'static/uploads'

collections:
  - name: 'events'  # Used in routes, e.g., /admin/collections/events
    label: 'Events'  # Used in the UI
    label_singular: 'Event'
    folder: 'content/events'  # The path to the folder where the documents are stored
    slug: '{{number}}'
    path: '{{slug}}/index'
    media_folder: ''
    create: true # Allow users to create new documents in this collection
    identifier_field: 'number'
    fields: # The fields for each document, usually in front matter
      - label: 'Event Number'
        name: 'number'
        widget: 'number'
        step: '0.1'
        hint: 'Event number without the "#" sign'
      - label: 'Event Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Speakers'
        name: 'speakers'
        widget: 'string'
      - label: 'Language'
        name: 'lang'
        widget: 'string'
        default: 'pl OR en'
      - label: 'Sponsors'
        name: 'sponsors'
        widget: 'list'
        hint: 'separate with commas "," '
      - label: 'Link to video recording'
        name: 'videoURL'
        widget: 'string'
        required: false
      - label: 'Draft?'
        name: 'draft'
        widget: 'boolean'
        default: false
      - label: 'Header Image'
        name: 'hero'
        widget: 'image'
        required: false
        allow_multiple: false
        hint: 'The file must be named "hero.jpg"'
      - label: 'Description'
        name: 'body'
        widget: 'markdown'
